### ISSUE TITLE
DEMO > search, search is not working

### ISSUE THREAD

**Issue by OskHa** [iamisti/mdDataTable#63]
just copied everything from the demo and the search is not working. 

had to change from ```{{(filteredItems = (nutritionList | filter: filterName))}}```

to ```{{filteredItems = (nutritionList | filter: filterName)}}```

(bracket around filteredItems)

**Comment by iamisti** [comment]
Which version exactly do you mean and which version did you use?

**Comment by OskHa** [comment]
```
"dependencies": {
    "jquery": "~2.1.4",
    "angular-material": "master",
    "components-font-awesome": "master",
    "angular-messages": "~1.4.8",
    "angular-route": "~1.4.8",
    "angular-loader": "~1.4.0",
    "angular-mocks": "~1.4.8",
    "angular-paging": "~2.1.0",
    "ngmap": "~1.16.7",
    "angular-environment": "~1.0.3",
    "mdDataTable": "~1.2.0",
    "underscore": "~1.8.3",
    "lodash": "~3.10.1",
    "angular-aria": "~1.4.9",
    "angular-animate": "~1.4.9"
  }
```

**Comment by OskHa** [comment]
also check the last comment.
https://github.com/iamisti/mdDataTable/issues/62

Cheers and have a great day

**Comment by iamisti** [comment]
Fixed with v1.5.0

**Comment by shriharry** [comment]
Hi Guys,

Nice plugin, But I am having issue in using 'mdt-row'. I followed this [https://github.com/iamisti/mdDataTable#data-row-attributes] to create table.  I always get typeError: _.get is not a function. I followed all steps discussed in issues. But not having any luck. Can you check my attachment if there is anything I am missing?

Cheers and thanks in advance. 

![1](https://cloud.githubusercontent.com/assets/6997180/17400134/d9f1fb38-5a63-11e6-8480-ef496f49f299.png)
![2](https://cloud.githubusercontent.com/assets/6997180/17400135/d9f67870-5a63-11e6-88c3-9ad15aed8889.png)

**Comment by OskHa** [comment]
just put lodash before, md-data-tbale in your scripts.

**Comment by shriharry** [comment]
Yes I changed order but It still throws same error.

This is my order now.

![3](https://cloud.githubusercontent.com/assets/6997180/17400926/3df63cc6-5a68-11e6-94d3-8a9a232426e1.png)

**Comment by OskHa** [comment]
Well i would suggest you to use a bild script that creates a vendor.js. Easiest is elixir from laravel, write your own gulp or check the webpack.

Loading scripts the way ur trying isnt the best way.

**Comment by shriharry** [comment]
I am using this angular-1 framework. In our project all dependencies are included in index.html page like this and not in vendor.js.  If I would have used angular-2, I could have tried to installed scripts in the way you told using composer build script.

**Comment by shriharry** [comment]
sorry for pain guys, but I just noticed that my loadash version is not latest. I included latest version, And it just resolved problem. Thank you so much.

Cheers and these are following sequences of files both of them just worked fine for me

![4](https://cloud.githubusercontent.com/assets/6997180/17402231/bd529b02-5a6f-11e6-8573-0ac22d010a83.png)

and this one too 

![5](https://cloud.githubusercontent.com/assets/6997180/17402289/1636f600-5a70-11e6-9d21-d5e0c827bdbc.png)

**Comment by iamisti** [comment]
I'm glad we could help!

**Comment by shriharry** [comment]
Sorry, to bother you again. 

I am unable to apply custom filter on mdt-rows attribute data field. I am applying it in this way.


```
 <mdt-table mdt-row="{'data': nutritionList  | myfilter:date1:date2,
                      'table-row-id-key': 'id',
                      'column-keys': ['id', 'name']}">
```

Is it right way to do this?

bcoz using ng-repeate attribute I was doing it in this way and it was working perfectly. 

`<mdt-row ng-repeat="feed in nutritionList  | myfilter:date1:date2">`


Will appreciate your help on this. Thanks.

**Comment by iamisti** [comment]
Hi @shriharry , I'd try to do it on the controller level with `$filter` service if didn't work for some reason.
But then maybe the better solution would be to use `mdt-row-paginator` and then you can filter and manipulate your data in one of your method in your controller.
